### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by DaGuich** [gulaki/code-timer#1]
It may be a good idea to package this code. So we can install it with pip or using a _setup.py_.
Also it may be a good idea to remove the underscore from the module/package name (For further information: https://www.python.org/dev/peps/pep-0008/#package-and-module-names).

**Comment by gulaki** [comment]
Thanks for this. I will learn more about packaging and making setups. 
How would I add this project to the pip list?

**Comment by DaGuich** [comment]
Thats a huge story. You may read [Packaging and Distributing Projects](https://packaging.python.org/tutorials/distributing-packages/).

**Comment by gulaki** [comment]
Thanks. I am only now beginning to understand VCS, github and packages.
